CREATE USER <EXPORTER_USER> WITH PASSWORD '<EXPORTER_USER_PASSWORD>';
ALTER USER <EXPORTER_USER> SET SEARCH_PATH TO public, pg_catalog;
GRANT CONNECT ON DATABASE <DATABASE> TO <EXPORTER_USER>;
GRANT USAGE ON SCHEMA public TO <EXPORTER_USER>;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO <EXPORTER_USER>;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO <EXPORTER_USER>;
