all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_gameland
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
  children:
    bastion:
      hosts:
        bastion_host:
          ansible_host: <IP>
    k3s:
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand="ssh -i ~/.ssh/id_rsa_gameland -W %h:22 bastion_host"
      children:
        control_plane:
          hosts:
            cp-1:
              ansible_host: <IP>
        workers:
          hosts:
            wk-1:
              ansible_host: <IP>
        database:
          hosts:
            db-1:
              ansible_host: <IP>
