export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "The Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Republic of the)",
  "Congo (Democratic Republic of the)",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of Timor-Leste",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of Korea (South Korea)",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tomé and Príncipe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Türkiye",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const postalCodePatterns: Record<string, RegExp> = {
  Afghanistan: /^\d{4}$/,
  "Åland Islands": /^\d{5}$/,
  Albania: /^\d{4}$/,
  Algeria: /^\d{5}$/,
  "American Samoa": /^\d{5}$/,
  Andorra: /^AD\d{3}$/,
  Angola: /^$/,
  Anguilla: /^[A-Za-z]{2}-\d{4}$/,
  "Antigua and Barbuda": /^\d{5}$/,
  Argentina: /^\d{4}$/,
  Armenia: /^\d{4}$/,
  Aruba: /^$/,
  Australia: /^\d{4}$/,
  Austria: /^\d{4}$/,
  Azerbaijan: /^AZ\s?\d{4}$/,
  Bahamas: /^$/,
  Bahrain: /^\d{3,4}$/,
  Bangladesh: /^\d{4}$/,
  Barbados: /^BB\d{5}$/,
  Belarus: /^\d{6}$/,
  Belgium: /^\d{4}$/,
  Belize: /^$/,
  Benin: /^$/,
  Bermuda: /^[A-Za-z]{2}\s?(?:[A-Za-z]{2}|\d{2})$/,
  Bhutan: /^\d{5}$/,
  Bolivia: /^\d{4}$/,
  "Bosnia and Herzegovina": /^\d{5}$/,
  Botswana: /^$/,
  Brazil: /^\d{5}-\d{3}$/,
  "British Virgin Islands": /^$/,
  Brunei: /^[A-Za-z]{2}\s?\d{4}$/,
  Bulgaria: /^\d{4}$/,
  "Burkina Faso": /^\d{5}$/,
  Burundi: /^$/,
  Cambodia: /^\d{5}$/,
  Cameroon: /^$/,
  Canada: /^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$/,
  "Cape Verde": /^\d{4}$/,
  "Cayman Islands": /^KY\d{2}-\d{4}$/,
  "Central African Republic": /^$/,
  Chad: /^$/,
  Chile: /^\d{7}$/,
  China: /^\d{6}$/,
  Colombia: /^\d{6}$/,
  Comoros: /^$/,
  "Congo (Brazzaville)": /^$/,
  "Congo (Kinshasa)": /^$/,
  "Cook Islands": /^$/,
  "Costa Rica": /^\d{5}$/,
  "Côte d'Ivoire": /^$/,
  Croatia: /^\d{5}$/,
  Cuba: /^\d{5}$/,
  Curaçao: /^$/,
  Cyprus: /^\d{4}$/,
  Czechia: /^\d{3} \d{2}$/,
  Denmark: /^\d{4}$/,
  Djibouti: /^$/,
  Dominica: /^$/,
  "Dominican Republic": /^\d{5}$/,
  Ecuador: /^\d{6}$/,
  Egypt: /^\d{5}$/,
  "El Salvador": /^1101$/,
  "Equatorial Guinea": /^$/,
  Eritrea: /^$/,
  Estonia: /^\d{5}$/,
  Eswatini: /^[A-Za-z]\d{3}$/,
  Ethiopia: /^\d{4}$/,
  "Falkland Islands": /^FIQQ\s?1ZZ$/,
  "Faroe Islands": /^FO-\d{3}$/,
  Fiji: /^\d{3}$/,
  Finland: /^\d{5}$/,
  France: /^\d{5}$/,
  "French Guiana": /^973\d{2}$/,
  "French Polynesia": /^987\d{2}$/,
  Gabon: /^\d{2}\s?[A-Za-z- ]\s?\d{2}$/,
  Gambia: /^$/,
  Georgia: /^\d{4}$/,
  Germany: /^\d{5}$/,
  Ghana: /^$/,
  Gibraltar: /^GX11\s?1AA$/,
  Greece: /^\d{3} \d{2}$/,
  Greenland: /^\d{4}$/,
  Grenada: /^\d{5}$/,
  Guadeloupe: /^971\d{2}$/,
  Guatemala: /^\d{5}$/,
  Guernsey: /^[A-Za-z]{2}\d\s?\d[A-Za-z]{2}$/,
  Guinea: /^$/,
  "Guinea-Bissau": /^\d{4}$/,
  Guyana: /^$/,
  Haiti: /^\d{4}$/,
  Honduras: /^\d{5}$/,
  "Hong Kong": /^$/,
  Hungary: /^\d{4}$/,
  Iceland: /^\d{3}$/,
  India: /^\d{6}$/,
  Indonesia: /^\d{5}$/,
  Iran: /^\d{5}-\d{5}$/,
  Iraq: /^\d{5}$/,
  Ireland: /^$/,
  "Isle of Man": /^IM\d{2}\s?\d[A-Za-z]{2}$/,
  Israel: /^\d{5}$/,
  Italy: /^\d{5}$/,
  Jamaica: /^$/,
  Japan: /^\d{3}-\d{4}$/,
  Jersey: /^[A-Za-z]{2}\d\s?\d[A-Za-z]{2}$/,
  Jordan: /^\d{5}$/,
  Kazakhstan: /^\d{6}$/,
  Kenya: /^\d{5}$/,
  Kiribati: /^$/,
  Kosovo: /^\d{5}$/,
  Kuwait: /^\d{5}$/,
  Kyrgyzstan: /^\d{6}$/,
  Laos: /^\d{5}$/,
  Latvia: /^[Ll][Vv][- ]?\d{4}$/,
  Lebanon: /^\d{4}\s?\d{4}$/,
  Lesotho: /^\d{3}$/,
  Liberia: /^\d{4}$/,
  Libya: /^\d{5}$/,
  Liechtenstein: /^\d{4}$/,
  Lithuania: /^[Ll][Tt][- ]?\d{5}$/,
  Luxembourg: /^\d{4}$/,
  Macau: /^$/,
  Macedonia: /^\d{4}$/,
  Madagascar: /^\d{3}$/,
  Malawi: /^$/,
  Malaysia: /^\d{5}$/,
  Maldives: /^\d{4,5}$/,
  Mali: /^$/,
  Malta: /^[A-Za-z]{3}\s?\d{4}$/,
  "Marshall Islands": /^\d{5}$/,
  Martinique: /^972\d{2}$/,
  Mauritania: /^$/,
  Mauritius: /^\d{5}$/,
  Mayotte: /^976\d{2}$/,
  Mexico: /^\d{5}$/,
  Micronesia: /^\d{5}(-\d{4})?$/,
  Moldova: /^[Mm][Dd][- ]?\d{4}$/,
  Monaco: /^980\d{2}$/,
  Mongolia: /^\d{5}$/,
  Montenegro: /^\d{5}$/,
  Montserrat: /^MSR\s?\d{4}$/,
  Morocco: /^\d{5}$/,
  Mozambique: /^\d{4}$/,
  Myanmar: /^\d{5}$/,
  Namibia: /^\d{5}$/,
  Nauru: /^$/,
  Nepal: /^\d{5}$/,
  Netherlands: /^\d{4}\s?[A-Za-z]{2}$/,
  "New Caledonia": /^988\d{2}$/,
  "New Zealand": /^\d{4}$/,
  Nicaragua: /^\d{5}$/,
  Niger: /^\d{4}$/,
  Nigeria: /^\d{6}$/,
  Niue: /^$/,
  "Norfolk Island": /^\d{4}$/,
  "North Macedonia": /^\d{4}$/,
  "Northern Mariana Islands": /^\d{5}$/,
  Norway: /^\d{4}$/,
  Oman: /^\d{3}$/,
  Pakistan: /^\d{5}$/,
  Palau: /^\d{5}$/,
  Palestine: /^$/,
  Panama: /^\d{6}$/,
  "Papua New Guinea": /^\d{3}$/,
  Paraguay: /^\d{4}$/,
  Peru: /^\d{5}$/,
  Philippines: /^\d{4}$/,
  "Pitcairn Islands": /^PCRN\s?1ZZ$/,
  Poland: /^\d{2}[- ]?\d{3}$/,
  Portugal: /^\d{4}[- ]?\d{3}$/,
  "Puerto Rico": /^\d{5}$/,
  Réunion: /^974\d{2}$/,
  Romania: /^\d{6}$/,
  Russia: /^\d{6}$/,
  Rwanda: /^$/,
  "Saint Barthélemy": /^$/,
  "Saint Helena": /^TDCU\s?1ZZ$/,
  "Saint Kitts and Nevis": /^\d{5}$/,
  "Saint Lucia": /^\d{5}$/,
  "Saint Martin": /^$/,
  "Saint Pierre and Miquelon": /^$/,
  "Saint Vincent and the Grenadines": /^\d{5}$/,
  Samoa: /^$/,
  "San Marino": /^\d{4}$/,
  "São Tomé and Príncipe": /^$/,
  "Saudi Arabia": /^\d{5}$/,
  Senegal: /^\d{5}$/,
  Serbia: /^\d{5}$/,
  Seychelles: /^$/,
  "Sierra Leone": /^$/,
  Singapore: /^\d{6}$/,
  "Sint Maarten": /^$/,
  Slovakia: /^\d{3} \d{2}$/,
  Slovenia: /^\d{4}$/,
  "Solomon Islands": /^$/,
  Somalia: /^$/,
  "South Africa": /^\d{4}$/,
  "South Korea": /^\d{5}$/,
  "South Sudan": /^$/,
  Spain: /^\d{5}$/,
  "Sri Lanka": /^\d{5}$/,
  Sudan: /^\d{5}$/,
  Suriname: /^$/,
  "Svalbard and Jan Mayen": /^\d{4}$/,
  Sweden: /^\d{3}\s?\d{2}$/,
  Switzerland: /^\d{4}$/,
  Syria: /^$/,
  Taiwan: /^\d{5}$/,
  Tajikistan: /^\d{6}$/,
  Tanzania: /^$/,
  Thailand: /^\d{5}$/,
  "Timor-Leste": /^$/,
  Togo: /^$/,
  Tokelau: /^$/,
  Tonga: /^$/,
  "Trinidad and Tobago": /^\d{6}$/,
  Tunisia: /^\d{4}$/,
  Turkey: /^\d{5}$/,
  Turkmenistan: /^\d{6}$/,
  "Turks and Caicos Islands": /^TKCA\s?1ZZ$/,
  Tuvalu: /^$/,
  "U.S. Virgin Islands": /^\d{5}$/,
  Uganda: /^$/,
  Ukraine: /^\d{5}$/,
  "United Arab Emirates": /^$/,
  "United Kingdom":
    /^([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z]{1,2}\d{1,2})|(([A-Za-z]{1,2}\d[A-Za-z])|([A-Za-z]{1,2}\d{1,2}[A-Za-z]))) \d[A-Za-z]{2})$/,
  "United States": /^\d{5}(?:-\d{4})?$/,
  Uruguay: /^\d{5}$/,
  Uzbekistan: /^\d{3}\s?\d{3}$/,
  Vanuatu: /^$/,
  Venezuela: /^\d{4}$/,
  Vietnam: /^\d{6}$/,
  "Wallis and Futuna": /^$/,
  "Western Sahara": /^$/,
  Yemen: /^\d{5}$/,
  Zambia: /^$/,
  Zimbabwe: /^\d{5}$/,
  default: /^.+$/,
};
