---
- name: Install K3s dependencies
  hosts: control_plane:workers:database
  become: true
  
  tasks:
    - name: Update apt cache and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - curl
        state: present
        