---
- name: Join K3s Workers and Database nodes to cluster
  hosts: workers:database
  become: true
  tasks:
    - name: Retrieve K3s token from first control plane node
      command: cat /var/lib/rancher/k3s/server/node-token
      delegate_to: "{{ groups['control_plane'][0] }}"
      register: k3s_token
      run_once: true

    - name: Set K3s token and control plane IP on localhost
      set_fact:
        k3s_token: "{{ k3s_token.stdout }}"
        control_plane_ip: "{{ hostvars[groups['control_plane'][0]].ansible_host }}"
      delegate_to: localhost
      run_once: true

    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ control_plane_ip }}:6443 K3S_TOKEN={{ k3s_token }} INSTALL_K3S_EXEC="--disable traefik" sh -
