---
- name: Join Kubernetes Workers and Database nodes to cluster
  hosts: workers:database
  become: true
  
  tasks:
    - name: Retrieve kubeadm join command from control plane
      command: kubeadm token create --print-join-command
      delegate_to: "{{ groups['control_plane'][0] }}"
      register: join_command
      run_once: true

    - name: Join node to Kubernetes cluster
      shell: "{{ join_command.stdout }} --ignore-preflight-errors=all"
      args:
        creates: /etc/kubernetes/kubelet.conf
