apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameland-ingress
  namespace: gameland
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /gameland
        pathType: Prefix
        backend:
          service:
            name: gameland
            port:
              number: 80
