apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameland-traefik-ingress
  namespace: gameland
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    traefik.ingress.kubernetes.io/router.middlewares: gameland-strip@gameland
    traefik.ingress.kubernetes.io/router.priority: "10"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
        - path: /gameland
          pathType: Prefix
          backend:
            service:
              name: gameland
              port:
                number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: gameland-strip
  namespace: gameland
spec:
  stripPrefix:
    prefixes:
      - /gameland
      