apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-traefik-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    traefik.ingress.kubernetes.io/router.middlewares: prometheus-strip@monitoring
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
        - path: /prometheus
          pathType: Prefix
          backend:
            service:
              name: kube-prometheus-stack-prometheus
              port:
                number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prometheus-strip
  namespace: monitoring
spec:
  stripPrefix:
    prefixes:
      - /prometheus
