nodeSelector:
  role: worker
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - paths:
        - path: /grafana
          pathType: Prefix
server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - paths:
          - path: /prometheus
            pathType: Prefix
