apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
        - path: /prometheus
          pathType: Prefix
          backend:
            service:
              name: prometheus
              port:
                number: 9090
